### ISSUE TITLE
Support CSRs with "challengePassword" and other fields

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/cfssl#115]
Currently, CFSSL fails on certain input CSRs. Specifically, requests with the "challengePassword" field cause CFSSL to return:
{"code":1003,"message":"asn1: structure error: sequence tag mismatch"}

Test data can be created with:
openssl req -nodes -newkey rsa:2048
with strings set for either of the two following fields:
- A challenge password []:
- An optional company name []:

**Comment by jacobhaven** [comment]
This is a problem in the `certificateRequest` struct inside Go crypto/x509/x509.go The asn1 unmarshaller reflects on it and attempts to parse the asn1 data. Apparently when it encounters one of these fields it attempts to interpret them as a sequence instead of a string. Updating the certificateRequest struct (and submitting the patch to Go upstream) should fix this...

**Comment by grittygrease** [comment]
@jacobhaven This can be closed once Go 1.5 is out, right?
