### ISSUE TITLE
Migrating to travis-ci.com

### ISSUE THREAD

**Issue by shivaburade** [cloudflare/cfssl#1194]
The travis-ci.org site will not run any new builds after June 15th, 2021.
Do we have any plans to migrate the repository to travis-ci.com? This is important for architectures like s390x which have CI support through Travis only.

**Comment by shivaburade** [comment]
I can see 3 new build requests for travis has been blocked because travis has now stopped support for org and insisting us to move to com. 
FYI - Travis.com is totally free for opensource project as per https://blog.travis-ci.com/oss-announcement

**Comment by nickysemenza** [comment]
Even before the travis switch, builds would sit in the queue for hours (you pay for what you get I guess) so I personally don't have high hope for using Travis in the future, but I'll see if we can give it a try.

I'm enjoying Github Actions and have migrated other repos there, but I haven't had time to do that here (it's a little more complex than `go test` due to the database tests). It looks like some other projects are testing on `s390x` via remote VMs: https://github.com/caddyserver/caddy/pull/3463/files, Perhaps we could migrate only the x86 tests to Actions (that way people get quick feedback in PRs if their tests fail).

**Comment by shivaburade** [comment]
Yes, we could move x86 builds on intel and have the s390x jobs run on Travis. Ideally, Travis jobs should not be in a queue for long. If it does happen I could take a look

**Comment by shivaburade** [comment]
Any Update?

**Comment by shivaburade** [comment]
Any Update?

**Comment by shivaburade** [comment]
Any Updates?

**Comment by shivaburade** [comment]
Any Updates?

**Comment by aborkar-ibm** [comment]
Thank you for the suggestion. We could close this issue as obsolete.
