### ISSUE TITLE
Unable to clear C, ST, O, OU, L in CSR

### ISSUE THREAD

**Issue by jcjones** [cloudflare/cfssl#156]
The recently added method `replaceSliceIfEmpty` from [aeaf899bba868e70ba78c478be99b7b4cb266915](https://github.com/cloudflare/cfssl/commit/aeaf899bba868e70ba78c478be99b7b4cb266915#diff-8d79bfc4bb0987be2c41ab248b24b30fR118) interferes with clearing unwanted Name fields.

The logic today chooses to copy the CSR-supplied Name fields if the signer.Subject object includes strings of length 0.

We need to be able to clear these fields, as we cannot trust the user's input, but passing strings of length 0 no longer does the trick. Of course, we can't send nil pointers either.

We need some better way to indicate to CFSSL to discard the CSR names.

**Comment by lziest** [comment]
if the signer.SignRequest contains a signer.Subject having non-empty Names, use those Names derived pkix.Name. Does that sound ok to you? @jcjones

**Comment by jcjones** [comment]
What "seemed" right and I tried was:

    req := signer.SignRequest{
		Request: csrPEM,
		Profile: ca.profile,
		Hosts:   hostNames,
		Subject: &signer.Subject{
			CN: commonName,
			Names: []cfcsr.Name{
				{
					C:  "",
					ST: "",
					L:  "",
					O:  "",
					OU: "",
				},
			},
		},
		SerialSeq: serialHex,
	}

**Comment by lziest** [comment]
OK, that's seems to me that we need to distinguish between unspecified default empty value and intentionally set empty value. Well, that is a Go issue.

**Comment by jcjones** [comment]
Agreed; other than a sentinel value I'm not sure what to do here. My go-fu is weak.

**Comment by jsha** [comment]
I think all we need here is to specify a whitelist of which Subject fields are allowed to be copied from the CSR. Fields not whitelisted must be empty in the signed certificate this could be part of the policy config.

We will probably want to use the same whitelisting mechanism to cover other fields of the CSR in general, like extensions.

As a short term fix, is it possible to revert https://github.com/cloudflare/cfssl/commit/aeaf899bba868e70ba78c478be99b7b4cb266915#diff-8d79bfc4bb0987be2c41ab248b24b30fR118 until we get whitelisting in place? Currently this is breaking tests in boulder (https://github.com/letsencrypt/boulder) and blocking work on Let's Encrypt.

Thanks,
Jacob

**Comment by kisom** [comment]
@jsha My current thought is this: we'll check whether any name fields in the Subject are set; if they are, we'll replace the name fields in the CSR with those from the Subject. Is that a good solution for you?

**Comment by jsha** [comment]
@kisom: Under that system, how can we specify "C must always be empty, regardless of what the CSR says?"

**Comment by kisom** [comment]
@jsha Okay, if you need that, I can add a mask field to the subject for
clearing fields. Would that work?

**Comment by jsha** [comment]
Another alternative: Right now we use the cfssl remote API. My understanding from @bifurcation is that @grittygrease asked us to use it so the API can be more thoroughly tested. But we could also embed the cfssl signing library into our own process and use the local signer. I think that would simplify things, reduce risk, and make it simpler for us to specify policies like this one that differ from Cloudflare's use cases. @grittygrease, how strong is your preference for use to use the remote API?

A mask field for Subject would also work, so long as it is positive. I.e., only fields listed in the mask get copied, rather than only those fields listed in the mask get cleared.

**Comment by grittygrease** [comment]
The intention was this:

having
C: ""
means clearing the value, no matter the value in the CSR

No C field in the JSON: use the value from CSR

**Comment by jsha** [comment]
@grittygrease: I think golang's default JSON parser does not allow you to tell the difference between an field that is missing from the JSON versus a field that has the zero value for its type. Each of these fields is of type string, and the zero value for string is "". So when we json.Unmarshal() into a struct, the string fields get the value "" even if they weren't present. Strings aren't nillable.

**Comment by grittygrease** [comment]
The main advantage of the split is for process separation between the API
and the key material, with the PKCS#11 interface this might no longer be an
issue. The other reason to use the JSON API is that it is more likely to be
stable. You can use the signer structures directly, but keep in mind that
we have not guaranteed API stability for our Go packages yet, and may yet
change things around.

**Comment by grittygrease** [comment]
I think you can do it with go interfaces:
http://attilaolah.eu/2013/11/29/json-decoding-in-go/

**Comment by jsha** [comment]
Skimming that article, it seems like the answer is to use pointers to strings rather than strings, so we get nullability. Quoting from https://golang.org/pkg/encoding/json/:

> To unmarshal JSON into a pointer, Unmarshal first handles the case of the JSON being the JSON literal null. In that case, Unmarshal sets the pointer to nil. Otherwise, Unmarshal unmarshals the JSON into the value pointed at by the pointer. If the pointer is nil, Unmarshal allocates a new value for it to point to.

So, looks like it's probably possible to make the API work the way you intended. Can I ask about your use cases and the expected use cases for other consumers of the API? Are inputs generally more-or-less trusted?

For Let's Encrypt we always want to default to not trusting the user input. For our use case, an API that defaults to trusting user input if you don't specifically override each field is non-optimal. My guess is that other API consumers would have similar requirements.

But, like I said earlier, we may be trying to solve this at the wrong level. What if we specified a policy mechanism that whitelists certain fields of the CSR that are allowed to be copied into the Certificate? This is something we need to do for Let's Encrypt. I had been planning to do it in Boulder (https://github.com/letsencrypt/boulder/pull/46), but it's looking like it makes more sense to do it in cfssl. I can write that patch if you agree it makes sense in cfssl.

**Comment by kisom** [comment]
@jsha What makes more sense to do now for what you need --- a whitelist, or the string pointers? I can add either, but I'd rather get done what's more helpful to you first.

**Comment by jsha** [comment]
The policy whitelist would help us solve the immediate problem, and would also resolve an outstanding task for us. So if you have the time for that, that would be awesome!

**Comment by kisom** [comment]
On it!

**Comment by jsha** [comment]
Great, thanks so much!

**Comment by kisom** [comment]
@jsha This is now implemented as of #157, #158 and is documented as in #161 --- it should be good to go.

**Comment by jsha** [comment]
Excellent, thanks!
