### ISSUE TITLE
Remove pkcs11 build tag?

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#262]
Right now the pkcs11 code is hidden behind the `pkcs11` build tag, so it doesn't get built unless you pass `-tags pkcs11` when you build. This is causing some toolchain issues for Boulder: In particular, the stock Godeps doesn't understand build tags, so we need to make sure everyone who updates our Godeps uses a patched copy.

Is there a strong reason for using the build tag? If not, I'd like to make it so pkcs11 support is unconditionally built.

**Comment by jmhodges** [comment]
This would be a really great change.

**Comment by kisom** [comment]
@jsha I think the biggest concern here was the cgo it pulls in. I'll do some testing here and see if this is still a problem; what will probably happen is that I'll change the tag to `nopkcs11`.

**Comment by jsha** [comment]
What's the concern with the cgo? That it might not build on some platforms?

Thanks,
Jacob

**Comment by kisom** [comment]
@jsha It requires `gcc` and some libtool development headers. This makes the build more complex for a feature few people seem to actually be using. We're looking into a solution for this, which will probably be providing pre-built packages.

**Comment by jmhodges** [comment]
Okay, so, if y'all aren't using it, and don't want to maintain it, we'd be happy to put this in another repository with the tag removed. 

I'm willing to rewrite our imports. While I don't think a libtool and gcc requirement is onerous since it only occurs if you actually depend on the package (which no non-pkcs11 code in this repo does), that is small change with a big win.

Other folks using it will rejoice even in that change of repo case because rewriting that import once is better than remembering the tag on all sorts of things (including godeps!).

**Comment by kisom** [comment]
We do use the PKCS11 tag, but our build tools work with build tags. We
do have enough users who would get a broken build that we don't want to
just jump into a solution without some additional testing; this testing
has had a lower priority due to other work needing to be done.

At some point tomorrow I'll have a PR that inverts the build tags:
instead of `pkcs11` to enable it, it'll be `nopkcs11` to disable it.

**Comment by kisom** [comment]
This is pull requested in #273. In the future, should such a change be required on a faster time scale, it will be faster for you to submit a PR for discussion.

**Comment by jmhodges** [comment]
Sorry, coming from a place where discussion happens before PRs. When you said you needed to think, I just read that and went with it and was going to wait for you to write back with an opinion.
