### ISSUE TITLE
Return scan results incrementally.

### ISSUE THREAD

**Issue by jacobhaven** [cloudflare/cfssl#269]
Currently, the results from `cfssl scan` are returned either all-together or not at all. In the case of a [timeout](https://github.com/cloudflare/cfssl/issues/235), this also means returning no information about what operations succeeded/didn't complete.

Having more fine-grained output would help debug issues in this case.

**Comment by taravancil** [comment]
I agree.

Do you think the scan should return results incrementally, or alternatively, return whatever results are available if/when the scan times out? Now that scans [run concurrently](https://github.com/cloudflare/cfssl/pull/278), I'm more inclined toward the latter.

Otherwise, individual scan results for different hosts will be returned in sequence, which isn't ideal.
