### ISSUE TITLE
Option to specify pathlen during sign or gencert for Intermediate CA

### ISSUE THREAD

**Issue by zaninime** [cloudflare/cfssl#495]
I didn't find an option to specify (aka change from the default value of 1) the pathlen constraint while issuing/signing a CA. Am I missing smth or it's just not implemented?

Thanks!

**Comment by dalbani** [comment]
See #417.

**Comment by benwhite-deltas** [comment]
'Intermediate CA' is the key here - cfssl prevents you from specifying a `ca` section, and therefore a `pathlen`, in the csr JSON file for anything other than a initca - see [this gist](https://gist.github.com/benwhite-deltas/a2ee7c5107bcc5a350bf541e363ac0ac) for reproduceable result.

This is odd, as after [some investigation](http://security.stackexchange.com/questions/119577/should-openssl-verify-recognise-an-exceeded-path-length-constraint-on-a-root) it seems Root CA certs' `pathlen` value is ignored whereas intermediate CAs `pathlen` value is respected.

I would hazard a guess that the cause of this issue is that the constraint of not allowing a `ca` section in a non-root csr should only be applied when the `is_ca` value of the policy being applied is `false`

**Comment by tam7t** [comment]
This is how I generate root/intermediate certs with `pathlen`'s:

### Generate a root (self signed)

`./root/root.json`
```
{
  "CN": "tam7t Root CA",
  "ca": {
    "pathlen": 2
  },
  "names": [
    {
      "C": "US",
      "L": "San Francisco",
      "O": "CloudFlare",
      "OU": "Systems Engineering",
      "ST": "California"
    }
  ]
}
```
```
$ cfssl genkey -initca root/root.json | cfssljson -bare root/root
```

### Generate an issuing certificate signing request

`./issuer/issuer.json`
```
{
  "CN": "tam7t Issuer CA",
  "ca": {
    "pathlen": 1
  },
  "names": [
    {
      "C": "US",
      "L": "San Francisco",
      "O": "CloudFlare",
      "OU": "Systems Engineering",
      "ST": "California"
    }
  ]
}
```

`./issuer/conf.json`
```
{
 "signing": {
   "default": {
     "usages": [
       "signing",
       "key encipherment",
       "cert sign",
       "crl sign"
      ],
      "expiry": "4320h",
      "is_ca": true
    }
  }
}
```

```
$ cfssl genkey -initca issuer/issuer.json | cfssljson -bare issuer/issuer
$ cfssl sign -ca root/root.pem -ca-key root/root-key.pem -config issuer/conf.json issuer/issuer.csr | cfssljson -bare issuer/issuer
```

and then use `openssl` to inspect the resulting certs:
```
$ openssl x509 -in root/root.pem -text
$ openssl x509 -in issuer/issuer.pem -text
```

**Comment by fhossain** [comment]
@tam7t can you try to generate an intermediate certificate with a value != 1. I was trying with 0 as well as 2 and neither works. The intermediate certificate shows up as pathlen 1 all the time. The case 0 is important to ensure that we can restrict an intermediate to issue client or server certificates only and not valid CA certificates.

**Comment by tam7t** [comment]
@fhossain ah, so in my example above `pathlen` does get set to `2` for the root cert and `1` to on the issuer. When I try with `pathlen` of `1` for the root and `0` for the issuer though the resulting certs both show a `pathlen` of `1`, that does seem like a bug (to me).

**Comment by lziest** [comment]
Hi, I remember I opened a issue for pathlen of 0 previously, but apparently I never actually submitted. Yes using pathlen=0 when init a CA is currently not supported in cfssl, which is due to an old bug (Go's default value making it impossible to distinguish a unspecified pathlen (unlimited pathlen) versus a pathlen=0 ).  see here https://golang.org/pkg/crypto/x509/#Certificate, `MaxPathLenZero bool`. We are working on supporting it.

**Comment by lziest** [comment]
And yes, currently intermediate CA's pathlen constraint is hardcoded to be 1.

**Comment by lziest** [comment]
#626 gives signer control on pathlen, and now signing config needs to be updated. Please check the new doc https://github.com/cloudflare/cfssl/blob/master/doc/cmd/cfssl.txt#L121
"is_ca" is replaced by "ca_constraint"
