### ISSUE TITLE
gencert with auth_key POST to /sign not /authsign

### ISSUE THREAD

**Issue by KevinHock** [cloudflare/cfssl#707]
So in the `Requesting Certificates` section of [Nick's CF blog post](https://blog.cloudflare.com/how-to-build-your-own-public-key-infrastructure/) he writes, "The gencert command will automatically handle the whole certificate generation process. It will create your private key, generate a CSR, send the CSR to the CA to be signed and return your signed certificate."

But I can't seem to be able to tell gencert, "Hey, I'm using a token, send the POST request to /api/v1/cfssl/authsign, not /sign!" Maybe I'm missing something :/

My config and the error are reproduced below:

```
ubuntu@ip:~/TestRun$ ../cfssl gencert -config ../authn_config_client.json ../csr_client.json
2016/12/28 21:54:02 [INFO] generate received request
2016/12/28 21:54:02 [INFO] received CSR
2016/12/28 21:54:02 [INFO] generating key: ecdsa-256
2016/12/28 21:54:02 [INFO] encoded CSR
2016/12/28 21:54:02 [ERROR] http error with http://172.28.150.40:8888/api/v1/cfssl/sign
{"code":7400,"message":"404 page not found\n"}

ubuntu@ip:~/TestRun$ cat ../authn_config_client.json 
{
  "auth_keys": {
    "key1": {
      "key": "1234",
      "type": "standard"
    }
  },
  "remotes": {
    "caserver": "172.28.150.40:8888"
  },
  "signing": {
    "default": {
      "auth_key": "key1",
      "remote": "caserver"
    }
  }
}
```

**Comment by jaydrogers** [comment]
Found this on a Google search. I know this is stale, but since it ranks high in Google for the error that I had I wanted to document how I fixed it.

I had this same issue. I followed the steps in [this comment](https://github.com/cloudflare/cfssl/issues/566#issuecomment-269070807). Once I added `auth_remote` to my client config, it forwarded the request to `authsign`.

Hope this helps!

**Comment by KevinHock** [comment]
Okay, thanks @jaydrogers 👍
