### ISSUE TITLE
Pass the CA and key to sign or gencert as text rather than files?

### ISSUE THREAD

**Issue by deitch** [cloudflare/cfssl#735]
Normally, the way to generate a cert is something like:

```
cfssl gencert -ca ca-cert.pem -ca-key ca-key.pem csr.json
```

Is there any way to pass it in a command-line, e.g.

```
-ca-material lots-of-text-here ...
```

Specifically, I am thinking of scenarios in which access to the filesystem is constrained, or we don't want to write the files out, everything in the docker cfssl/cfssl container (without volume mounts), etc.

**Comment by gebi** [comment]
Something like this would be awesome, though i'd prefer to put e.g the CA key into the process environment.

Our usecase would be certificate creation from ansible and the CA key is ansible-vault encrypted.

**Comment by deitch** [comment]
Yeah, I am all for passing it into the environment. Either way, as long as we can pass the key material as data and not just a file.

**Comment by kisom** [comment]
There isn't a way to do this right now, no; it's not something we're likely to prioritise working on here right now because it's not how we're using it (generally for something similar, we write out files to a tmpfs). That being said, we're happy to review PRs. 

One approach might be to support a similar construct to that used in the [auth package](https://github.com/cloudflare/cfssl/blob/master/auth/auth.go#L50), such as prefixing an environment variable with "env:".

Reading from standard input is trickier, because there are multiple items that you might want to read from stdin (keys, config files with API keys, etc) and it becomes an issue of figuring out what order things need to be in and what's expected to come in.

**Comment by deitch** [comment]
> Reading from standard input is trickier, because there are multiple items that you might want to read from stdin (keys, config files with API keys, etc) and it becomes an issue of figuring out what order things need to be in and what's expected to come in.

Yeah, that's true. Of course cfssl already _outputs_ several things that way by using json, so that could be a valid way to _input_ things.

**Comment by kisom** [comment]
It could --- we'd just need to figure out what that looks like and how it'd work.

**Comment by tkellen** [comment]
Hi all!

It looks like some functionality was implemented around this. Was a new version incorporating these changes released?

**Comment by tkellen** [comment]
PS: If support for this is in the source tree and just waiting on someone to do a release I'd be happy to tackle that with a bit of guidance.

**Comment by kisom** [comment]
I believe there is support for this in the tree, we have a few things to close out before our next release.
