### ISSUE TITLE
How to get the Trusted CA Chain(not bundle) using CFSSL Api ?

### ISSUE THREAD

**Issue by saivamsi75** [cloudflare/cfssl#783]
I have set up the CFSSL using 'cfssl' command  like creating root CA, intermediate CA.
Now from a remote machine, I am able to  request for Peer/client/server certificates signed by intermediate CA through REST API . Unfortunately, my application which verifies the certificates doesn't support certificate bundle, so I have to provide the trusted chain as separate files. so my question, is there a way to request the CA trusted chain from an API ??

Note: This is not an issue , it is more of enquiring how to. As there is no CFSSL mailing list, I am using this space to post my query.

**Comment by lziest** [comment]
cfssl info may help you to get CA certificate.

**Comment by lazize** [comment]
How to create the chain locally? should I use `cfssl bundle`?

I don't have an intermediate certificate, just "root" and the "server". So after create and sign my "server" certificate I want to have a chain of `"server" + "root"`.

What I am doing: 
`cfssl bundle -cert myserver.pem -ca-bundle ca.pem  | cfssljson -bare myserver`

It creates the file `myserver-bundle.pem`, but if we get a diff between bundle file and server certificate file, both are basically the same:
```shell
diff myserver-bundle.pem myserver.pem
16c16
< -----END CERTIFICATE-----
\ No newline at end of file
---
> -----END CERTIFICATE-----
```

**Comment by lziest** [comment]
ideally, the root is stored in the trust store, i.e. there is no need to present it as a chain, because it is simply trusted.

**Comment by annakz** [comment]
Hi,
I'm trying to create the chain locally as well (as @lazize described), and wanted to join the question- why in the resulting "bundle" value I get only 1 certificate, and it is the leaf certificate?
Thanks

**Comment by jvettraino** [comment]
I have a similar need to get the public Root Cert from a remote CFSSL instance.  For our use case we need it to setup a trust store on a server that is dynamically started (want all certificates to come from the remote CFSSL instance that are needed for the server trust).

Is there anyway to get the root public key for this use case?

**Comment by cbroglie** [comment]
@jvettraino see https://github.com/cloudflare/cfssl/issues/783#issuecomment-314903099

**Comment by Punkoivan** [comment]
Hey folks. Sorry for necroposting, I know it's 4 years passed, but going to comment since this is the only info about that.
So, FWIW.
@jvettraino was googling today and found that issue.
Comment with "RTFM" helped a little, but the for final solution I have to go to the code.
try this and make sure you have env required:
`curl -s -H "Content-Type: application/json" -X POST -d '{"profile": "default"}' https://${CF_URL}/api/v1/cfssl/info`
and extract cert with jq:
`curl -s -H "Content-Type: application/json" -X POST -d '{"profile": "default"}' https://${CF_URL}/api/v1/cfssl/info | jq -r ".result.certificate" > cert.pem`
