### ISSUE TITLE
Error signing intermediate CA

### ISSUE THREAD

**Issue by s0l4r** [cloudflare/cfssl#865]
Hi,

I'm having problems setting up cfssl with root+intermediate. The last step (signing) fails with "CSR Decode failed". I'm not sure what could be wrong, the DEBUG log doesn't say much and the config-syntax seems to be ok.

Setup:
cfssl version
Version: 1.2.0
Revision: dev
Runtime: go1.6

Config:
ca-config.json:
```
{
    "signing": {
        "default": {
            "expiry": "262800h"
        },
        "profiles": {
            "intermediate": {
                "expiry": "262800h",
                "ca_constraint": {
                   "is_ca": true,
                   "max_path_len":1
                },
                "usages": [
                    "digital signature",
                    "signing",
                    "key encipherment",
                    "cert sign",
                    "crl sign"
                ]
            },
            "server": {
                "expiry": "43800h",
                "usages": [
                    "signing",
                    "key encipherment",
                    "client auth",
                    "server auth"
                ]
            },
            "client": {
                "expiry": "43800h",
                "usages": [
                    "signing",
                    "key encipherment",
                    "client auth"
                ]
            }
        }
    }
}
``` 
ca-root-csr.json:
```
{
    "CN": "Root CA v3",
    "key": {
        "algo": "ecdsa",
        "size": 256
    },
    "ca": {
        "expiry": "262800h",
        "pathlen": 1
    },
    "names": [
        {
            "C": "FO",
            "L": "Foo",
            "O": "Bar",
            "ST": "Foobar"
        }
    ]
}
```

ca-intermediate-csr.json:
```
{
    "CN": "Intermediate CA v3",
    "key": {
        "algo": "ecdsa",
        "size": 256
    },
    "ca": {
        "expiry": "262800h",
        "pathlen": 0
    },
    "names": [
        {
            "C": "FO",
            "L": "Foo",
            "O": "Bar",
            "ST": "Foobar"
        }
    ]
}
```

Run commands:
```
cfssl genkey -initca ca-root-csr.json | cfssljson -bare ca-root
cfssl genkey -initca ca-intermediate-csr.json | cfssljson -bare ca-intermediate
```
^Above gives no errors.

Log output when signing:
```
cfssl sign -profile intermediate -ca ca-root.pem -ca-key ca-root-key.pem -config ca-config.json ca-intermediate-csr.json | cfssljson -bare ca-intermediate
{"code":9002,"message":"CSR Decode failed"}
```

**Comment by mingqing** [comment]
cfssl sign -profile 'intermediate' -ca ca-root.pem -ca-key ca-root-key.pem -config ca-config.json {CSR-FILE}  | cfssljson -bare ca-intermediate

{CSR-FILE} not ca-intermediate-csr.json, may be ca-intermediate.csr

**Comment by s0l4r** [comment]
Thank you, it works!

**Comment by ricketybridge** [comment]
I followed these directions, but what happens is that the intermediate CA's `-initca` command creates a certificate, which the root signs, creating a new certificate. Then, when the intermediate CA signs a client certificate, `openssl verify` doesn't recognize the client certificate as having been signed by the signed intermediate certificate, but by the original unsigned one. But the original is a self-signed certificate, breaking the chain to the root. What am I missing here? Shouldn't it be possible to verify the client certificate via a command like this?:

`openssl verify -CAfile intermediate_signed.pem client.pem`

However, this gives me the error:

`error 20 at 0 depth lookup:unable to get local issuer certificate`

And `openssl verify -CAfile intermediate_original.pem client.pem` gets the OK. However, `openssl verify -CAfile ca-root.pem intermediate_original.pem` gets the self-signed error. Is this expected behavior?
